const weatherConditionCodes = [
  {
    code: 1000,
    day: 'Sunny',
    night: 'Clear',
    icon: 113,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Sol',
      night_text: 'Céu limpo',
    },
  },
  {
    code: 1003,
    day: 'Partly Cloudy',
    night: 'Partly Cloudy',
    icon: 116,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Parcialmente nublado',
      night_text: 'Parcialmente nublado',
    },
  },
  {
    code: 1006,
    day: 'Cloudy',
    night: 'Cloudy',
    icon: 119,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Nublado',
      night_text: 'Nublado',
    },
  },
  {
    code: 1009,
    day: 'Overcast',
    night: 'Overcast',
    icon: 122,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Encoberto',
      night_text: 'Encoberto',
    },
  },
  {
    code: 1030,
    day: 'Mist',
    night: 'Mist',
    icon: 143,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Neblina',
      night_text: 'Neblina',
    },
  },
  {
    code: 1063,
    day: 'Patchy rain nearby',
    night: 'Patchy rain nearby',
    icon: 176,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Possibilidade de chuva irregular',
      night_text: 'Possibilidade de chuva irregular',
    },
  },
  {
    code: 1066,
    day: 'Patchy snow nearby',
    night: 'Patchy snow nearby',
    icon: 179,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Possibilidade de neve irregular',
      night_text: 'Possibilidade de neve irregular',
    },
  },
  {
    code: 1069,
    day: 'Patchy sleet nearby',
    night: 'Patchy sleet nearby',
    icon: 182,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Possibilidade de neve molhada irregular',
      night_text: 'Possibilidade de neve molhada irregular',
    },
  },
  {
    code: 1072,
    day: 'Patchy freezing drizzle nearby',
    night: 'Patchy freezing drizzle nearby',
    icon: 185,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Possibilidade de chuvisco gelado irregular',
      night_text: 'Possibilidade de chuvisco gelado irregular',
    },
  },
  {
    code: 1087,
    day: 'Thundery outbreaks in nearby',
    night: 'Thundery outbreaks in nearby',
    icon: 200,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Possibilidade de trovoada',
      night_text: 'Possibilidade de trovoada',
    },
  },
  {
    code: 1114,
    day: 'Blowing snow',
    night: 'Blowing snow',
    icon: 227,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Rajadas de vento com neve',
      night_text: 'Rajadas de vento com neve',
    },
  },
  {
    code: 1117,
    day: 'Blizzard',
    night: 'Blizzard',
    icon: 230,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Nevasca',
      night_text: 'Nevasca',
    },
  },
  {
    code: 1135,
    day: 'Fog',
    night: 'Fog',
    icon: 248,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Nevoeiro',
      night_text: 'Nevoeiro',
    },
  },
  {
    code: 1147,
    day: 'Freezing fog',
    night: 'Freezing fog',
    icon: 260,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Nevoeiro gelado',
      night_text: 'Nevoeiro gelado',
    },
  },
  {
    code: 1150,
    day: 'Patchy light drizzle',
    night: 'Patchy light drizzle',
    icon: 263,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuvisco irregular',
      night_text: 'Chuvisco irregular',
    },
  },
  {
    code: 1153,
    day: 'Light drizzle',
    night: 'Light drizzle',
    icon: 266,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuvisco',
      night_text: 'Chuvisco',
    },
  },
  {
    code: 1168,
    day: 'Freezing drizzle',
    night: 'Freezing drizzle',
    icon: 281,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuvisco gelado',
      night_text: 'Chuvisco gelado',
    },
  },
  {
    code: 1171,
    day: 'Heavy freezing drizzle',
    night: 'Heavy freezing drizzle',
    icon: 284,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuvisco forte gelado',
      night_text: 'Chuvisco forte gelado',
    },
  },
  {
    code: 1180,
    day: 'Patchy light rain',
    night: 'Patchy light rain',
    icon: 293,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva fraca irregular',
      night_text: 'Chuva fraca irregular',
    },
  },
  {
    code: 1183,
    day: 'Light rain',
    night: 'Light rain',
    icon: 296,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva fraca',
      night_text: 'Chuva fraca',
    },
  },
  {
    code: 1186,
    day: 'Moderate rain at times',
    night: 'Moderate rain at times',
    icon: 299,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Períodos de chuva moderada',
      night_text: 'Períodos de chuva moderada',
    },
  },
  {
    code: 1189,
    day: 'Moderate rain',
    night: 'Moderate rain',
    icon: 302,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva moderada',
      night_text: 'Chuva moderada',
    },
  },
  {
    code: 1192,
    day: 'Heavy rain at times',
    night: 'Heavy rain at times',
    icon: 305,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Períodos de chuva forte',
      night_text: 'Períodos de chuva forte',
    },
  },
  {
    code: 1195,
    day: 'Heavy rain',
    night: 'Heavy rain',
    icon: 308,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva forte',
      night_text: 'Chuva forte',
    },
  },
  {
    code: 1198,
    day: 'Light freezing rain',
    night: 'Light freezing rain',
    icon: 311,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva fraca e gelada',
      night_text: 'Chuva fraca e gelada',
    },
  },
  {
    code: 1201,
    day: 'Moderate or heavy freezing rain',
    night: 'Moderate or heavy freezing rain',
    icon: 314,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva gelada moderada ou forte',
      night_text: 'Chuva gelada moderada ou forte',
    },
  },
  {
    code: 1204,
    day: 'Light sleet',
    night: 'Light sleet',
    icon: 317,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva fraca com neve',
      night_text: 'Chuva fraca com neve',
    },
  },
  {
    code: 1207,
    day: 'Moderate or heavy sleet',
    night: 'Moderate or heavy sleet',
    icon: 320,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva forte ou moderada com neve',
      night_text: 'Chuva forte ou moderada com neve',
    },
  },
  {
    code: 1210,
    day: 'Patchy light snow',
    night: 'Patchy light snow',
    icon: 323,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Queda de neve irregular e fraca',
      night_text: 'Queda de neve irregular e fraca',
    },
  },
  {
    code: 1213,
    day: 'Light snow',
    night: 'Light snow',
    icon: 326,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Queda de neve fraca',
      night_text: 'Queda de neve fraca',
    },
  },
  {
    code: 1216,
    day: 'Patchy moderate snow',
    night: 'Patchy moderate snow',
    icon: 329,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Queda de neve moderada e irregular',
      night_text: 'Queda de neve moderada e irregular',
    },
  },
  {
    code: 1219,
    day: 'Moderate snow',
    night: 'Moderate snow',
    icon: 332,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Queda de neve moderada',
      night_text: 'Queda de neve moderada',
    },
  },
  {
    code: 1222,
    day: 'Patchy heavy snow',
    night: 'Patchy heavy snow',
    icon: 335,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Queda de neve forte e irregular',
      night_text: 'Queda de neve forte e irregular',
    },
  },
  {
    code: 1225,
    day: 'Heavy snow',
    night: 'Heavy snow',
    icon: 338,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Neve intensa',
      night_text: 'Neve intensa',
    },
  },
  {
    code: 1237,
    day: 'Ice pellets',
    night: 'Ice pellets',
    icon: 350,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Granizo',
      night_text: 'Granizo',
    },
  },
  {
    code: 1240,
    day: 'Light rain shower',
    night: 'Light rain shower',
    icon: 353,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Aguaceiros fracos',
      night_text: 'Aguaceiros fracos',
    },
  },
  {
    code: 1243,
    day: 'Moderate or heavy rain shower',
    night: 'Moderate or heavy rain shower',
    icon: 356,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Aguaceiros moderados ou fortes',
      night_text: 'Aguaceiros moderados ou fortes',
    },
  },
  {
    code: 1246,
    day: 'Torrential rain shower',
    night: 'Torrential rain shower',
    icon: 359,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva torrencial',
      night_text: 'Chuva torrencial',
    },
  },
  {
    code: 1249,
    day: 'Light sleet showers',
    night: 'Light sleet showers',
    icon: 362,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Aguaceiros fracos com neve',
      night_text: 'Aguaceiros fracos com neve',
    },
  },
  {
    code: 1252,
    day: 'Moderate or heavy sleet showers',
    night: 'Moderate or heavy sleet showers',
    icon: 365,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Aguaceiros moderados ou fortes com neve',
      night_text: 'Aguaceiros moderados ou fortes com neve',
    },
  },
  {
    code: 1255,
    day: 'Light snow showers',
    night: 'Light snow showers',
    icon: 368,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva fraca com neve',
      night_text: 'Chuva fraca com neve',
    },
  },
  {
    code: 1258,
    day: 'Moderate or heavy snow showers',
    night: 'Moderate or heavy snow showers',
    icon: 371,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva moderada ou forte com neve',
      night_text: 'Chuva moderada ou forte com neve',
    },
  },
  {
    code: 1261,
    day: 'Light showers of ice pellets',
    night: 'Light showers of ice pellets',
    icon: 374,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Aguaceiros fracos com granizo',
      night_text: 'Aguaceiros fracos com granizo',
    },
  },
  {
    code: 1264,
    day: 'Moderate or heavy showers of ice pellets',
    night: 'Moderate or heavy showers of ice pellets',
    icon: 377,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Aguaceiros moderados ou fortes com granizo',
      night_text: 'Aguaceiros moderados ou fortes com granizo',
    },
  },
  {
    code: 1273,
    day: 'Patchy light rain in area with thunder',
    night: 'Patchy light rain in area with thunder',
    icon: 386,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva fraca irregular com trovoada',
      night_text: 'Chuva fraca irregular com trovoada',
    },
  },
  {
    code: 1276,
    day: 'Moderate or heavy rain in area with thunder',
    night: 'Moderate or heavy rain in area with thunder',
    icon: 389,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Chuva moderada ou forte com trovoada',
      night_text: 'Chuva moderada ou forte com trovoada',
    },
  },
  {
    code: 1279,
    day: 'Patchy light snow in area with thunder',
    night: 'Patchy light snow in area with thunder',
    icon: 392,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Neve fraca irregular com trovoada',
      night_text: 'Neve fraca irregular com trovoada',
    },
  },
  {
    code: 1282,
    day: 'Moderate or heavy snow in area with thunder',
    night: 'Moderate or heavy snow in area with thunder',
    icon: 395,
    portuguese: {
      lang_iso: 'pt',
      day_text: 'Neve moderada ou forte com trovoada',
      night_text: 'Neve moderada ou forte com trovoada',
    },
  },
];

export default weatherConditionCodes;
